# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20170929_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydeduplication',
            name='status',
            field=models.CharField(choices=[('p', '\u041d\u0435 \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u0435\u043d\u043e'), ('m', "\u041e\u0431'\u0454\u0434\u043d\u0430\u0442\u0438"), ('a', '\u0417\u0430\u043b\u0438\u0448\u0438\u0442\u0438 \u0432\u0441\u0435 \u044f\u043a \u0454'), ('-', '---------------'), ('d1', '\u0412\u0438\u0434\u0430\u043b\u0438\u0442\u0438 \u043f\u0435\u0440\u0448\u0443'), ('d2', '\u0412\u0438\u0434\u0430\u043b\u0438\u0442\u0438 \u0434\u0440\u0443\u0433\u0443'), ('dd', '\u0412\u0438\u0434\u0430\u043b\u0438\u0442\u0438 \u0432\u0441\u0456')], db_index=True, default='p', max_length=2, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
