# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:53
from __future__ import unicode_literals

from django.db import migrations
from tasks.models import BeneficiariesMatching


def save_json_fields_again(apps, schema_editor):
    # Ugly but works
    for bf in BeneficiariesMatching.objects.all():
        bf.person_json = bf.person_json
        bf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20171022_0208'),
    ]

    operations = [
        migrations.RunPython(save_json_fields_again)
    ]
