# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0027_auto_20180112_1510")]

    operations = [
        migrations.AlterField(
            model_name="edrmonitoring",
            name="edr_date",
            field=models.DateField(
                verbose_name="\u0414\u0430\u0442\u0430 \u0435\u043a\u0441\u043f\u043e\u0440\u0442\u0443 \u0437 \u0404\u0414\u0420"
            ),
        )
    ]
