# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0029_edrmonitoring_person_id")]

    operations = [
        migrations.AlterField(
            model_name="edrmonitoring",
            name="applied",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="\u0417\u0430\u0441\u0442\u043e\u0441\u043e\u0432\u0430\u043d\u043e",
            ),
        )
    ]
