# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20180219_2155'),
        ('tasks', '0030_auto_20180220_1405'),
    ]

    operations = [
    ]
