# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0141_auto_20180227_0323"),
        ("tasks", "0031_merge_20180227_0322"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminationNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="\u0421\u0442\u0432\u043e\u0440\u0435\u043d\u043e",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="\u0417\u043c\u0456\u043d\u0435\u043d\u043e",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "p",
                                "\u041d\u0435 \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u0435\u043d\u043e",
                            ),
                            (
                                "a",
                                "\u0417\u0430\u0441\u0442\u043e\u0441\u0443\u0432\u0430\u0442\u0438 \u0437\u043c\u0456\u043d\u0443",
                            ),
                            (
                                "i",
                                "\u0406\u0433\u043d\u043e\u0440\u0443\u0432\u0430\u0442\u0438 \u0437\u043c\u0456\u043d\u0443",
                            ),
                            (
                                "r",
                                "\u041f\u043e\u0442\u0440\u0435\u0431\u0443\u0454 \u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u043e\u0457 \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u043a\u0438",
                            ),
                        ],
                        db_index=True,
                        default="p",
                        max_length=1,
                        verbose_name="\u0421\u0442\u0430\u0442\u0443\u0441",
                    ),
                ),
                (
                    "new_person_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "\u041f\u043e\u043c\u0435\u0440"),
                            (
                                2,
                                "\u0417\u0432\u0456\u043b\u044c\u043d\u0438\u0432\u0441\u044f/\u0441\u043a\u043b\u0430\u0432 \u043f\u043e\u0432\u043d\u043e\u0432\u0430\u0436\u0435\u043d\u043d\u044f",
                            ),
                            (
                                3,
                                "\u0427\u043b\u0435\u043d \u0441\u0456\u043c'\u0457 - \u041f\u0415\u041f \u043f\u043e\u043c\u0435\u0440",
                            ),
                            (
                                4,
                                "\u0427\u043b\u0435\u043d \u0441\u0456\u043c'\u0457 - \u041f\u0415\u041f \u043f\u0440\u0438\u043f\u0438\u043d\u0438\u0432 \u0431\u0443\u0442\u0438 \u041f\u0415\u041f\u043e\u043c",
                            ),
                            (
                                5,
                                "\u0417\u043c\u0456\u043d\u0438 \u0443 \u0437\u0430\u043a\u043e\u043d\u043e\u0434\u0430\u0432\u0441\u0442\u0432\u0456 \u0449\u043e \u0432\u0438\u0437\u043d\u0430\u0447\u0430\u0454 \u0441\u0442\u0430\u0442\u0443\u0441 \u041f\u0415\u041f\u0430",
                            ),
                            (
                                6,
                                "\u0417\u043c\u0456\u043d\u0438 \u0444\u043e\u0440\u043c\u0438 \u0432\u043b\u0430\u0441\u043d\u043e\u0441\u0442\u0456 \u044e\u0440. \u043e\u0441\u043e\u0431\u0438 \u043f\u043e\u0441\u0430\u0434\u0430 \u0432 \u043a\u043e\u0442\u0440\u0456\u0439 \u0434\u0430\u0432\u0430\u043b\u0430 \u0441\u0442\u0430\u0442\u0443\u0441 \u041f\u0415\u041f\u0430",
                            ),
                        ],
                        null=True,
                        verbose_name="\u041c\u043e\u0436\u043b\u0438\u0432\u0430 \u043f\u0440\u0438\u0447\u0438\u043d\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f",
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        help_text="\u0412\u043a\u0430\u0437\u0443\u0454\u0442\u044c\u0441\u044f \u0440\u0435\u0430\u043b\u044c\u043d\u0430 \u0434\u0430\u0442\u0430 \u0437\u043c\u0456\u043d\u0438 \u0431\u0435\u0437 \u0432\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f 3 \u0440\u043e\u043a\u0456\u0432 (\u0440\u0435\u0430\u043b\u044c\u043d\u0430 \u0434\u0430\u0442\u0430 \u0437\u0432\u0456\u043b\u044c\u043d\u0435\u043d\u043d\u044f, \u0442\u043e\u0449\u043e)",
                        null=True,
                        verbose_name="\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f",
                    ),
                ),
                (
                    "termination_date_details",
                    models.IntegerField(
                        choices=[
                            (
                                0,
                                "\u0422\u043e\u0447\u043d\u0430 \u0434\u0430\u0442\u0430",
                            ),
                            (
                                1,
                                "\u0420\u0456\u043a \u0442\u0430 \u043c\u0456\u0441\u044f\u0446\u044c",
                            ),
                            (
                                2,
                                "\u0422\u0456\u043b\u044c\u043a\u0438 \u0440\u0456\u043a",
                            ),
                        ],
                        default=0,
                        verbose_name="\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f: \u0442\u043e\u0447\u043d\u0456\u0441\u0442\u044c",
                    ),
                ),
                (
                    "pep_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435",
                    ),
                ),
                (
                    "pep_position",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="\u041f\u043e\u0441\u0430\u0434\u0430",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.Person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="\u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447",
                    ),
                ),
            ],
            options={
                "verbose_name": "\u041a\u0430\u043d\u0434\u0438\u0434\u0430\u0442 \u043d\u0430 \u0432\u0438\u043b\u0456\u0442",
                "verbose_name_plural": "\u041a\u0430\u043d\u0434\u0438\u0434\u0430\u0442\u0438 \u043d\u0430 \u0432\u0438\u043b\u0456\u0442",
            },
        ),
        migrations.AlterUniqueTogether(
            name="terminationnotice",
            unique_together=set(
                [("person", "pep_name", "termination_date", "termination_date_details")]
            ),
        ),
        migrations.AlterIndexTogether(
            name="terminationnotice",
            index_together=set(
                [("person", "pep_name", "termination_date", "termination_date_details")]
            ),
        ),
    ]
