# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_terminationnotice_termination_date_ceiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationnotice',
            name='action',
            field=models.CharField(choices=[('review', '\u041f\u0435\u0440\u0435\u0432\u0456\u0440\u0438\u0442\u0438 \u0432\u0440\u0443\u0447\u043d\u0443'), ('change_type', "\u0417\u043c\u0456\u043d\u0438\u0442\u0438 \u0442\u0438\u043f \u041f\u0415\u041f \u043d\u0430 \u043f\u043e\u0432'\u044f\u0437\u0430\u043d\u0443 \u043e\u0441\u043e\u0431\u0443"), ('fire', '\u041f\u0440\u0438\u043f\u0438\u043d\u0438\u0442\u0438 \u041f\u0415\u041f\u0441\u0442\u0432\u043e')], db_index=True, default='fire', max_length=12, verbose_name='\u0414\u0456\u044f'),
        ),
    ]
