# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_adhocmatches_matched_json_hash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdHocMatches',
            new_name='AdHocMatch',
        ),
    ]
