# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 22:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def move_json_fields(apps, schema_editor):
    match = apps.get_model("tasks", "AdHocMatch")

    for m in match.objects.all():
        m.matched_dj_json = m.matched_json
        m.save()


class Migration(migrations.Migration):

    dependencies = [("tasks", "0043_terminationnotice_applied")]

    operations = [
        migrations.AddField(
            model_name="adhocmatch",
            name="matched_dj_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                null=True,
                verbose_name="\u0417\u043d\u0430\u0439\u0434\u0435\u043d\u043e \u0432 \u0434\u0430\u0442\u0430\u0441\u0435\u0442\u0456",
            ),
        ),
        migrations.RunPython(move_json_fields, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name="adhocmatch", name="matched_json"),
        migrations.RenameField(
            model_name="adhocmatch", old_name="matched_dj_json", new_name="matched_json"
        ),
    ]
