# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-13 23:57
from __future__ import unicode_literals

from django.db import migrations


def repack_json(apps, schema_editor):
    match = apps.get_model("tasks", "AdHocMatch")

    for m in match.objects.all():
        if isinstance(m.matched_json, list):
            m.matched_json = dict(m.matched_json)
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_auto_20180614_0200'),
    ]

    operations = [
        migrations.RunPython(
            repack_json, reverse_code=migrations.RunPython.noop),
    ]
