# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("tasks", "0046_auto_20180614_0257")]

    operations = [
        migrations.AlterField(
            model_name="adhocmatch",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adhoc_matches",
                to="core.Person",
            ),
        )
    ]
