# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-03 16:54
from __future__ import unicode_literals

from django.db import migrations


def populate_names(apps, schema_editor):
    def get_name(doc, fields):
        return " ".join(filter(None, (doc.get(x, None) for x in fields)))

    matches = apps.get_model("tasks", "AdHocMatch")

    for m in matches.objects.filter(dataset_id="cvk_2015"):
        m.name_in_dataset = get_name(m.matched_json, ["name"])
        m.save()


class Migration(migrations.Migration):

    dependencies = [("tasks", "0049_adhocmatch_name_in_dataset")]

    operations = [
        migrations.RunPython(populate_names, reverse_code=migrations.RunPython.noop)
    ]
