# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tasks", "0054_smidacandidate")]

    operations = [
        migrations.AddField(
            model_name="smidacandidate",
            name="matched_json_hash",
            field=models.CharField(
                max_length=40, null=True, verbose_name="\u0425\u0435\u0448"
            ),
        ),
        migrations.AddField(
            model_name="smidacandidate",
            name="smida_level",
            field=models.IntegerField(
                null=True,
                verbose_name="\u0412\u0456\u0434\u0441\u0442\u0430\u043d\u044c \u0432\u0456\u0434 \u0434\u0435\u0440\u0436\u0430\u0432\u0438",
            ),
        ),
        migrations.AddField(
            model_name="smidacandidate",
            name="smida_shares",
            field=models.FloatField(
                null=True,
                verbose_name="\u0427\u0430\u0441\u0442\u043a\u0430 \u0434\u0435\u0440\u0436\u0430\u0432\u0438",
            ),
        ),
    ]
