# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_auto_20180904_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smidacandidate',
            name='smida_prev_position',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u041f\u043e\u043f\u0435\u0440\u0435\u0434\u043d\u044f \u043f\u043e\u0441\u0430\u0434\u0430 \u0437\u0456 \u0437\u0432\u0456\u0442\u0443'),
        ),
    ]
