# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_smidacandidate_smida_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smidacandidate',
            name='smida_level',
            field=models.IntegerField(null=True, verbose_name='\u0412\u0456\u0434\u0441\u0442\u0430\u043d\u044c'),
        ),
        migrations.AlterField(
            model_name='smidacandidate',
            name='smida_position_body',
            field=models.CharField(choices=[('sc', '\u041f\u0440\u0430\u0432\u043b\u0456\u043d\u043d\u044f'), ('wc', '\u041d\u0430\u0433\u043b\u044f\u0434\u043e\u0432\u0430 \u0440\u0430\u0434\u0430'), ('ac', '\u0420\u0435\u0432\u0456\u0437\u0456\u0439\u043d\u0430 \u043a\u043e\u043c\u0456\u0441\u0456\u044f'), ('a', '\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440\u0456\u044f'), ('s', '\u0421\u0435\u043a\u0440\u0435\u0442\u0430\u0440\u0456\u0430\u0442'), ('o', '\u0406\u043d\u0448\u0435'), ('h', '\u041a\u0435\u0440\u0456\u0432\u043d\u0438\u043a')], max_length=2, verbose_name='\u041e\u0440\u0433\u0430\u043d'),
        ),
        migrations.AlterField(
            model_name='smidacandidate',
            name='smida_prev_position',
            field=models.TextField(blank=True, verbose_name='\u041f\u043e\u043f\u0435\u0440\u0435\u0434\u043d\u044f \u043f\u043e\u0441\u0430\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='smidacandidate',
            name='smida_shares',
            field=models.FloatField(null=True, verbose_name='% \u0434\u0435\u0440\u0436\u0430\u0432\u0438'),
        ),
    ]
