# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-08 18:42
from __future__ import unicode_literals

from django.db import migrations


def fix_genders(apps, schema_editor):
    AdHocMatch = apps.get_model("tasks", "AdHocMatch")

    for m in (
        AdHocMatch.objects.filter(dataset_id="cvk_2015", applied=True, status="a")
        .nocache()
        .iterator()
    ):
        if m.person and "громадянка" in m.person.wiki_uk.lower():
            m.person.wiki_uk = m.person.wiki_uk.replace("балотувався", "балотувалася")
            m.person.save()


class Migration(migrations.Migration):

    dependencies = [("tasks", "0060_auto_20180907_1322")]

    operations = [
        migrations.RunPython(fix_genders, reverse_code=migrations.RunPython.noop)
    ]
