# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0061_auto_20180908_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='smidacandidate',
            name='dt_of_first_entry',
            field=models.DateTimeField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0435\u0440\u0448\u043e\u0457 \u043f\u043e\u044f\u0432\u0438 \u0432 \u0437\u0432\u0456\u0442\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='smidacandidate',
            name='dt_of_last_entry',
            field=models.DateTimeField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0441\u0442\u0430\u043d\u043d\u044c\u043e\u0457 \u043f\u043e\u044f\u0432\u0438 \u0432 \u0437\u0432\u0456\u0442\u0430\u0445'),
        ),
    ]
