# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-25 17:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0062_auto_20181221_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAISCompany',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u0442\u0432\u043e\u0440\u0435\u043d\u043e')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0417\u043c\u0456\u043d\u0435\u043d\u043e')),
                ('company_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u0404\u0414\u0420\u041f\u041e\u0423')),
                ('status', models.CharField(choices=[('p', '\u041d\u0435 \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u0435\u043d\u043e'), ('a', '\u0417\u0430\u0441\u0442\u043e\u0441\u043e\u0432\u0430\u043d\u043e'), ('i', '\u0406\u0433\u043d\u043e\u0440\u0443\u0432\u0430\u0442\u0438'), ('r', '\u041f\u043e\u0442\u0440\u0435\u0431\u0443\u0454 \u0434\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u043e\u0457 \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u043a\u0438')], db_index=True, default='p', max_length=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('created', models.BooleanField(verbose_name='\u041a\u043e\u043c\u043f\u0430\u043d\u0456\u0457 \u043d\u0435\u043c\u0430 \u0432 \u043d\u0430\u0448\u0456\u0439 \u0431\u0430\u0437\u0456')),
                ('matched_json', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='\u0417\u0430\u043f\u0438\u0441 \u043d\u0430 \u0441\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f')),
                ('company_name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0457')),
                ('company_status', models.CharField(max_length=100, verbose_name='\u041f\u043e\u0442\u043e\u0447\u043d\u0438\u0439 \u0441\u0442\u0430\u043d')),
                ('company_type', models.CharField(choices=[('political_party', '\u041f\u0430\u0440\u0442\u0456\u044f'), ('affiliated_with_pep', "\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0430 \u0437 \u041f\u0415\u041f"), ('state_enterprise', '\u0414\u0435\u0440\u0436. \u0432\u043b\u0430\u0441\u043d\u0456\u0441\u0442\u044c'), ('public_office', '\u0414\u0435\u0440\u0436.\u043e\u0440\u0433\u0430\u043d'), ('service_provider', '\u041d\u0430\u0434\u0430\u0432\u0430\u0447 \u043f\u043e\u0441\u043b\u0443\u0433'), ('bank', '\u0411\u0430\u043d\u043a')], db_index=True, max_length=20, verbose_name='\u0422\u0438\u043f \u043a\u043e\u043c\u043f\u0430\u043d\u0456\u0457')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
