# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-17 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0011_auto_20160223_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanneritem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagebanneritem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagebanneritem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagecolumn',
            name='columnfields_ptr',
        ),
        migrations.RemoveField(
            model_name='homepagecolumn',
            name='page',
        ),
        migrations.DeleteModel(
            name='ColumnFields',
        ),
        migrations.DeleteModel(
            name='HomePageBannerItem',
        ),
        migrations.DeleteModel(
            name='HomePageColumn',
        ),
    ]
