# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0110_auto_20170814_0226")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="\u0406\u043d\u0434\u0435\u043a\u0441",
            ),
        )
    ]
