# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:57
from __future__ import unicode_literals

from django.db import migrations
from unicodecsv import DictReader


def load_banks(apps, schema_editor):
    country_model = apps.get_model("core", "Country")
    company_model = apps.get_model("core", "Company")
    company2country_model = apps.get_model("core", "Company2Country")

    with open("core/dicts/foreign_banks.csv", "r") as fp:
        r = DictReader(fp)

        for l in r:
            try:
                country = country_model.objects.get(
                    name_en__iexact=l["country"].strip()
                )
            except country_model.DoesNotExist:
                print("Cannot find country %s" % l["country"])
                continue

            try:
                bank, _ = company_model.objects.get_or_create(
                    name_en=l["name"].strip(),
                    defaults={
                        "name_uk": l["name"].strip(),
                        "zip_code": l["zip_code"].strip(),
                        "city_en": l["city"].strip(),
                        "street_en": l["street"].strip(),
                        "appt_en": l["appt"].strip(),
                        "city_uk": l["city"].strip(),
                        "street_uk": l["street"].strip(),
                        "appt_uk": l["appt"].strip(),
                    },
                )

                company2country_model.objects.get_or_create(
                    from_company=bank,
                    to_country=country,
                    relationship_type="registered_in",
                )
            except company_model.MultipleObjectsReturned:
                print("Cannot find country %s" % l["country"])
                continue


class Migration(migrations.Migration):

    dependencies = [("core", "0111_auto_20170823_1557")]

    operations = [migrations.RunPython(load_banks)]
