# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 23:26
from __future__ import unicode_literals
import re

from django.db import migrations
from django.db.models import Q


def fix_ciprus_companies(apps, schema_editor):
    Company = apps.get_model("core.Company")

    for c in Company.objects.filter(
        Q(edrpou__istartswith="HE")
        | Q(edrpou__istartswith="ΗΕ")
        | Q(edrpou__istartswith="H.E.")
    ):

        c.edrpou = re.sub("^HE\s?", "HE ", c.edrpou)
        c.edrpou = re.sub("^ΗΕ\s?", "HE ", c.edrpou)
        c.edrpou = re.sub("^H\.E\.\s?", "HE ", c.edrpou)
        c.edrpou = re.sub("^Η\.E\.\s?", "HE ", c.edrpou)
        c.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0118_auto_20170924_0223")]

    operations = [migrations.RunPython(fix_ciprus_companies)]
