# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:23
from __future__ import unicode_literals

from django.db import migrations


def normalize_edrpous(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    for c in Company.objects.all():
        edrpou = c.edrpou or ""
        if " " in edrpou and edrpou.strip() and ":" not in edrpou:
            c.edrpou = c.edrpou.replace(" ", "")
            c.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0120_auto_20170924_0242")]

    operations = [migrations.RunPython(normalize_edrpous)]
