# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 22:45
from __future__ import unicode_literals

from django.db import migrations


def migrate_bank_customers(apps, schema_editor):
    Person2Company = apps.get_model("core", "Person2Company")

    for p2c in Person2Company.objects.filter(
        relationship_type_uk="Клієнт", declarations__isnull=False
    ):
        p2c.relationship_type_uk = "Клієнт банку"
        p2c.relationship_type_en = "Bank customer"
        p2c.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0123_auto_20171002_1403")]

    operations = [migrations.RunPython(migrate_bank_customers)]
