# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 01:45
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0126_auto_20171104_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_title', models.TextField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043a\u043b\u0430\u0434: \u0441\u043a\u043b\u0430\u0434 \u0412\u0420 7-\u0433\u043e \u0441\u043a\u043b\u0438\u043a\u0430\u043d\u043d\u044f', verbose_name="\u041d\u0430\u0437\u0432\u0430 \u0434\u043e\u043a\u0430\u0437\u0443 \u0437\u0432'\u044f\u0437\u043a\u0443")),
                ('proof', models.TextField(blank=True, verbose_name="\u0430\u0431\u043e \u043f\u043e\u0441\u0438\u043b\u0430\u043d\u043d\u044f \u043d\u0430 \u0434\u043e\u043a\u0430\u0437 \u0437\u0432'\u044f\u0437\u043a\u0443")),
                ('proof_document', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document', verbose_name="\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442-\u0434\u043e\u043a\u0430\u0437 \u0437\u0432'\u044f\u0437\u043a\u0443")),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('proof_title_en', models.TextField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043a\u043b\u0430\u0434: \u0441\u043a\u043b\u0430\u0434 \u0412\u0420 7-\u0433\u043e \u0441\u043a\u043b\u0438\u043a\u0430\u043d\u043d\u044f', null=True, verbose_name="\u041d\u0430\u0437\u0432\u0430 \u0434\u043e\u043a\u0430\u0437\u0443 \u0437\u0432'\u044f\u0437\u043a\u0443")),
                ('proof_title_uk', models.TextField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043a\u043b\u0430\u0434: \u0441\u043a\u043b\u0430\u0434 \u0412\u0420 7-\u0433\u043e \u0441\u043a\u043b\u0438\u043a\u0430\u043d\u043d\u044f', null=True, verbose_name="\u041d\u0430\u0437\u0432\u0430 \u0434\u043e\u043a\u0430\u0437\u0443 \u0437\u0432'\u044f\u0437\u043a\u0443")),
            ],
            options={
                'verbose_name': "\u041f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043d\u044f \u0437\u0432'\u044f\u0437\u043a\u0443",
                'verbose_name_plural': "\u041f\u0456\u0434\u0442\u0432\u0435\u0440\u0434\u0436\u0435\u043d\u043d\u044f \u0437\u0432'\u044f\u0437\u043a\u0456\u0432",
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0424\u0456\u043d\u0430\u043d\u0441\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0424\u0456\u043d\u0430\u043d\u0441\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0424\u0456\u043d\u0430\u043d\u0441\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_founders',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', verbose_name='\u0406\u043d\u0448\u0456 \u0437\u0430\u0441\u043d\u043e\u0432\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_founders_en',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0437\u0430\u0441\u043d\u043e\u0432\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_founders_uk',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0437\u0430\u0441\u043d\u043e\u0432\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_managers',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', verbose_name='\u0406\u043d\u0448\u0456 \u043a\u0435\u0440\u0443\u044e\u0447\u0456'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_managers_en',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u043a\u0435\u0440\u0443\u044e\u0447\u0456'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_managers_uk',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u043a\u0435\u0440\u0443\u044e\u0447\u0456'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_owners',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', verbose_name='\u0406\u043d\u0448\u0456 \u0432\u043b\u0430\u0441\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_owners_en',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0432\u043b\u0430\u0441\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='other_owners_uk',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0432\u043b\u0430\u0441\u043d\u0438\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sanctions',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0421\u0430\u043d\u043a\u0446\u0456\u0457'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sanctions_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0430\u043d\u043a\u0446\u0456\u0457'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sanctions_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0430\u043d\u043a\u0446\u0456\u0457'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wiki',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wiki_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wiki_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='declarationextra',
            name='address',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='declarationextra',
            name='note',
            field=core.fields.RedactorField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_assets',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0421\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_assets_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_assets_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_convictions',
            field=core.fields.RedactorField(blank=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0443\u0434\u0438\u043c\u043e\u0441\u0442\u0456'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_convictions_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0443\u0434\u0438\u043c\u043e\u0441\u0442\u0456'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_convictions_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0443\u0434\u0438\u043c\u043e\u0441\u0442\u0456'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_crimes',
            field=core.fields.RedactorField(blank=True, verbose_name='\u041a\u0440\u0438\u043c\u0456\u043d\u0430\u043b\u044c\u043d\u0456 \u043f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_crimes_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041a\u0440\u0438\u043c\u0456\u043d\u0430\u043b\u044c\u043d\u0456 \u043f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_crimes_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041a\u0440\u0438\u043c\u0456\u043d\u0430\u043b\u044c\u043d\u0456 \u043f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_manhunt',
            field=core.fields.RedactorField(blank=True, verbose_name='\u041f\u0435\u0440\u0435\u0431\u0443\u0432\u0430\u043d\u043d\u044f \u0443 \u0440\u043e\u0437\u0448\u0443\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_manhunt_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0435\u0431\u0443\u0432\u0430\u043d\u043d\u044f \u0443 \u0440\u043e\u0437\u0448\u0443\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_manhunt_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0435\u0431\u0443\u0432\u0430\u043d\u043d\u044f \u0443 \u0440\u043e\u0437\u0448\u0443\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_sanctions',
            field=core.fields.RedactorField(blank=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0430\u043d\u043a\u0446\u0456\u0439'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_sanctions_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0430\u043d\u043a\u0446\u0456\u0439'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reputation_sanctions_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0430\u043d\u043a\u0446\u0456\u0439'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wiki',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wiki_draft',
            field=core.fields.RedactorField(blank=True, verbose_name='\u0427\u0435\u0440\u043d\u0435\u0442\u043a\u0430 \u0432\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u0456'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wiki_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wiki_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AlterField(
            model_name='person2person',
            name='relationship_details',
            field=core.fields.RedactorField(blank=True, verbose_name="\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0438\u0439 \u043e\u043f\u0438\u0441 \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
        migrations.AlterField(
            model_name='person2person',
            name='relationship_details_en',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name="\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0438\u0439 \u043e\u043f\u0438\u0441 \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
        migrations.AlterField(
            model_name='person2person',
            name='relationship_details_uk',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name="\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0438\u0439 \u043e\u043f\u0438\u0441 \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
    ]
