# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("core", "0128_auto_20171109_0358")]

    operations = [
        migrations.RemoveField(model_name="person2person", name="declaration"),
        migrations.AlterField(
            model_name="declaration",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="\u0406\u043c'\u044f"
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=40,
                verbose_name="\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435",
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="source",
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
