# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 18:14
from __future__ import unicode_literals

from django.db import migrations


def toggle_existing_declarations(apps, schema_editor):
    Declaration = apps.get_model("core.Declaration")

    Declaration.objects.update(to_link=True)


class Migration(migrations.Migration):

    dependencies = [("core", "0132_auto_20180103_2011")]

    operations = [migrations.RunPython(toggle_existing_declarations)]
