# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0136_auto_20180104_0122"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="last_change",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="\u0414\u0430\u0442\u0430 \u043e\u0441\u0442\u0430\u043d\u043d\u044c\u043e\u0457 \u0437\u043c\u0456\u043d\u0438 \u043f\u0440\u043e\u0444\u0456\u043b\u044f \u0430\u0431\u043e \u0437\u0432'\u044f\u0437\u043a\u0456\u0432 \u043f\u0440\u043e\u0444\u0456\u043b\u044f",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="last_editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="\u0410\u0432\u0442\u043e\u0440 \u0437\u043c\u0456\u043d\u0438",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="last_change",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="\u0414\u0430\u0442\u0430 \u043e\u0441\u0442\u0430\u043d\u043d\u044c\u043e\u0457 \u0437\u043c\u0456\u043d\u0438 \u043f\u0440\u043e\u0444\u0456\u043b\u044f \u0430\u0431\u043e \u0437\u0432'\u044f\u0437\u043a\u0456\u0432 \u043f\u0440\u043e\u0444\u0456\u043b\u044f",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="last_editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="\u0410\u0432\u0442\u043e\u0440 \u0437\u043c\u0456\u043d\u0438",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="reason_of_termination",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "\u041f\u043e\u043c\u0435\u0440"),
                    (2, "\u0417\u0432\u0456\u043b\u044c\u043d\u0438\u0432\u0441\u044f"),
                    (
                        3,
                        "\u0427\u043b\u0435\u043d \u0441\u0456\u043c'\u0457 - \u041f\u0415\u041f \u043f\u0440\u0438\u043f\u0438\u043d\u0438\u0432 \u0431\u0443\u0442\u0438 \u041f\u0415\u041f\u043e\u043c",
                    ),
                    (
                        4,
                        "\u0417\u043c\u0456\u043d\u0438 \u0443 \u0437\u0430\u043a\u043e\u043d\u043e\u0434\u0430\u0432\u0441\u0442\u0432\u0456 \u0449\u043e \u0432\u0438\u0437\u043d\u0430\u0447\u0430\u0454 \u0441\u0442\u0430\u0442\u0443\u0441 \u041f\u0415\u041f\u0430",
                    ),
                    (
                        5,
                        "\u0417\u043c\u0456\u043d\u0438 \u0444\u043e\u0440\u043c\u0438 \u0432\u043b\u0430\u0441\u043d\u043e\u0441\u0442\u0456 \u044e\u0440. \u043e\u0441\u043e\u0431\u0438 \u043f\u043e\u0441\u0430\u0434\u0430 \u0432 \u043a\u043e\u0442\u0440\u0456\u0439 \u0434\u0430\u0432\u0430\u043b\u0430 \u0441\u0442\u0430\u0442\u0443\u0441 \u041f\u0415\u041f\u0430",
                    ),
                ],
                null=True,
                verbose_name="\u041f\u0440\u0438\u0447\u0438\u043d\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="termination_date",
            field=models.DateField(
                blank=True,
                help_text="\u0412\u043a\u0430\u0437\u0443\u0454\u0442\u044c\u0441\u044f \u0440\u0435\u0430\u043b\u044c\u043d\u0430 \u0434\u0430\u0442\u0430 \u0437\u043c\u0456\u043d\u0438 \u0431\u0435\u0437 \u0432\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f 3 \u0440\u043e\u043a\u0456\u0432 (\u0440\u0435\u0430\u043b\u044c\u043d\u0430 \u0434\u0430\u0442\u0430 \u0437\u0432\u0456\u043b\u044c\u043d\u0435\u043d\u043d\u044f, \u0442\u043e\u0449\u043e)",
                null=True,
                verbose_name="\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="termination_date_details",
            field=models.IntegerField(
                choices=[
                    (0, "\u0422\u043e\u0447\u043d\u0430 \u0434\u0430\u0442\u0430"),
                    (
                        1,
                        "\u0420\u0456\u043a \u0442\u0430 \u043c\u0456\u0441\u044f\u0446\u044c",
                    ),
                    (2, "\u0422\u0456\u043b\u044c\u043a\u0438 \u0440\u0456\u043a"),
                ],
                default=0,
                verbose_name="\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u043f\u0438\u043d\u0435\u043d\u043d\u044f \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u041f\u0415\u041f: \u0442\u043e\u0447\u043d\u0456\u0441\u0442\u044c",
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="submitted",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="\u041f\u043e\u0434\u0430\u043d\u0430",
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="to_link",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="\u0414\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0456\u044f \u0434\u043b\u044f \u043f\u0440\u043e\u0444\u0456\u043b\u0456\u0432",
            ),
        ),
    ]
