# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0136_auto_20180104_0122")]

    operations = [
        migrations.AlterField(
            model_name="declaration",
            name="submitted",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="\u041f\u043e\u0434\u0430\u043d\u0430",
            ),
        ),
        migrations.AlterField(
            model_name="declaration",
            name="to_link",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="\u0414\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0456\u044f \u0434\u043b\u044f \u043f\u0440\u043e\u0444\u0456\u043b\u0456\u0432",
            ),
        ),
    ]
