# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20180220_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('export_companies', 'Can export the dataset of companies'),), 'verbose_name': '\u042e\u0440\u0438\u0434\u0438\u0447\u043d\u0430 \u043e\u0441\u043e\u0431\u0430', 'verbose_name_plural': '\u042e\u0440\u0438\u0434\u0438\u0447\u043d\u0456 \u043e\u0441\u043e\u0431\u0438'},
        ),
    ]
