# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0138_auto_20180220_1420")]

    operations = [
        migrations.AlterUniqueTogether(
            name="declaration", unique_together=set([("person", "declaration_id")])
        )
    ]
