# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20180219_2155'),
        ('core', '0139_auto_20180221_2202'),
    ]

    operations = [
    ]
