# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0142_auto_20180301_2143")]

    operations = [
        migrations.AlterField(
            model_name="declaration",
            name="person",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declarations",
                to="core.Person",
            ),
        )
    ]
