# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-25 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0144_person_declarator_id"),
        ("core", "0145_auto_20180511_0206"),
    ]

    operations = []
