# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-25 09:20
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_merge_20180925_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='appt_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u2116 \u0431\u0443\u0434\u0438\u043d\u043a\u0443, \u043e\u0444\u0456\u0441\u0443'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0424\u0456\u043d\u0430\u043d\u0441\u043e\u0432\u0430 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u044f'),
        ),
        migrations.AddField(
            model_name='company',
            name='city_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041c\u0456\u0441\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='\u041f\u043e\u0432\u043d\u0430 \u043d\u0430\u0437\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_founders_ru',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0437\u0430\u0441\u043d\u043e\u0432\u043d\u0438\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_managers_ru',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u043a\u0435\u0440\u0443\u044e\u0447\u0456'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_owners_ru',
            field=core.fields.RedactorField(blank=True, help_text='\u0427\u0435\u0440\u0435\u0437 \u043a\u043e\u043c\u0443, \u043d\u0435 PEP', null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0432\u043b\u0430\u0441\u043d\u0438\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_recipient_ru',
            field=models.CharField(blank=True, help_text='\u042f\u043a\u0449\u043e \u043d\u0435 \u0454 PEP\u043e\u043c', max_length=200, null=True, verbose_name='\u0411\u0435\u043d\u0435\u0444\u0456\u0446\u0456\u0430\u0440\u0456\u0439'),
        ),
        migrations.AddField(
            model_name='company',
            name='sanctions_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0430\u043d\u043a\u0446\u0456\u0457'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u043a\u043e\u0440\u043e\u0447\u0435\u043d\u0430 \u043d\u0430\u0437\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='company',
            name='street_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0412\u0443\u043b\u0438\u0446\u044f'),
        ),
        migrations.AddField(
            model_name='company',
            name='wiki_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='office_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0412\u0456\u0434\u043e\u043c\u0441\u0442\u0432\u043e'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='position_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u041f\u043e\u0441\u0430\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='declaration',
            name='region_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0420\u0435\u0433\u0456\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041b\u044e\u0434\u0441\u044c\u043a\u0430 \u043d\u0430\u0437\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='person',
            name='also_known_as_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u0406\u043d\u0448\u0456 \u0456\u043c\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='person',
            name='city_of_birth_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041c\u0456\u0441\u0442\u043e \u043d\u0430\u0440\u043e\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='person',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name="\u0406\u043c'\u044f"),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
        migrations.AddField(
            model_name='person',
            name='patronymic_ru',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u041f\u043e \u0431\u0430\u0442\u044c\u043a\u043e\u0432\u0456'),
        ),
        migrations.AddField(
            model_name='person',
            name='reputation_assets_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0421\u0442\u0430\u0442\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='person',
            name='reputation_convictions_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0443\u0434\u0438\u043c\u043e\u0441\u0442\u0456'),
        ),
        migrations.AddField(
            model_name='person',
            name='reputation_crimes_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041a\u0440\u0438\u043c\u0456\u043d\u0430\u043b\u044c\u043d\u0456 \u043f\u0440\u043e\u0432\u0430\u0434\u0436\u0435\u043d\u043d\u044f'),
        ),
        migrations.AddField(
            model_name='person',
            name='reputation_manhunt_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0435\u0431\u0443\u0432\u0430\u043d\u043d\u044f \u0443 \u0440\u043e\u0437\u0448\u0443\u043a\u0443'),
        ),
        migrations.AddField(
            model_name='person',
            name='reputation_sanctions_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u041d\u0430\u044f\u0432\u043d\u0456\u0441\u0442\u044c \u0441\u0430\u043d\u043a\u0446\u0456\u0439'),
        ),
        migrations.AddField(
            model_name='person',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wiki_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name='\u0412\u0456\u043a\u0456-\u0441\u0442\u0430\u0442\u0442\u044f'),
        ),
        migrations.AddField(
            model_name='person2company',
            name='relationship_type_ru',
            field=models.TextField(blank=True, null=True, verbose_name="\u0422\u0438\u043f \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
        migrations.AddField(
            model_name='person2person',
            name='relationship_details_ru',
            field=core.fields.RedactorField(blank=True, null=True, verbose_name="\u0414\u0435\u0442\u0430\u043b\u044c\u043d\u0438\u0439 \u043e\u043f\u0438\u0441 \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
        migrations.AddField(
            model_name='relationshipproof',
            name='proof_title_ru',
            field=models.TextField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043a\u043b\u0430\u0434: \u0441\u043a\u043b\u0430\u0434 \u0412\u0420 7-\u0433\u043e \u0441\u043a\u043b\u0438\u043a\u0430\u043d\u043d\u044f', null=True, verbose_name="\u041d\u0430\u0437\u0432\u0430 \u0434\u043e\u043a\u0430\u0437\u0443 \u0437\u0432'\u044f\u0437\u043a\u0443"),
        ),
    ]
