# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0146_auto_20180811_2340")]

    operations = [
        migrations.AddField(
            model_name="declaration",
            name="doc_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="\u0422\u0438\u043f \u0434\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0456\u0457",
            ),
        )
    ]
