# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:45
from __future__ import unicode_literals

from django.db import migrations


def add_doctypes(apps, schema_editor):
    Declaration = apps.get_model("core", "Declaration")

    for d in Declaration.objects.all():
        d.doc_type = d.source["intro"].get("doc_type", "Щорічна")
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_declaration_doc_type'),
    ]

    operations = [
        migrations.RunPython(
            add_doctypes, reverse_code=migrations.RunPython.noop),
    ]
