# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0150_auto_20180911_0101")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="_last_modified",
            field=models.DateTimeField(
                null=True,
                verbose_name="\u041e\u0441\u0442\u0430\u043d\u043d\u044f \u0437\u043c\u0456\u043d\u0430",
            ),
        )
    ]
