# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-10 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0151_auto_20180911_0130")]

    operations = [
        migrations.RunSQL(
            """
            CREATE FUNCTION sync_lastmod() RETURNS trigger AS $$
            BEGIN
              NEW._last_modified := NOW();

              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_person2company
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();


            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_person2person
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();



            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_person2country
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();



            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_person
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();



            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_company
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();


            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_company2company
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();


            CREATE TRIGGER
              sync_lastmod
            BEFORE UPDATE ON
              core_company2country
            FOR EACH ROW
            WHEN (OLD.* IS DISTINCT FROM NEW.*)
            EXECUTE PROCEDURE
              sync_lastmod();

            """,
            """
                DROP FUNCTION sync_lastmod CASCADE;
            """,
        )
    ]
