# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20180911_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='en_wiki_url',
            field=models.URLField(blank=True, max_length=1023, verbose_name='\u041f\u043e\u0441\u0438\u043b\u0430\u043d\u043d\u044f \u043d\u0430 En \u0432\u0456\u043a\u0456'),
        ),
        migrations.AddField(
            model_name='person',
            name='ru_wiki_url',
            field=models.URLField(blank=True, max_length=1023, verbose_name='\u041f\u043e\u0441\u0438\u043b\u0430\u043d\u043d\u044f \u043d\u0430 Ru \u0432\u0456\u043a\u0456'),
        ),
        migrations.AddField(
            model_name='person',
            name='uk_wiki_url',
            field=models.URLField(blank=True, max_length=1023, verbose_name='\u041f\u043e\u0441\u0438\u043b\u0430\u043d\u043d\u044f \u043d\u0430 Ua \u0432\u0456\u043a\u0456'),
        ),
    ]
