# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-07 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_auto_20180911_1325'),
        ('core', '0147_auto_20180925_1220'),
    ]

    operations = [
    ]
