# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0154_merge_20181007_1459"),
        ("core", "0145_auto_20181009_0108"),
    ]

    operations = []
