# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_merge_20181108_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ogrn_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u041e\u0413\u0420\u041d'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0435\u0431\u0441\u0430\u0439\u0442'),
        ),
        migrations.AddField(
            model_name='person',
            name='inn',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u0406\u041d\u041d'),
        ),
    ]
