# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_auto_20190512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('other', '\u0406\u043d\u0448\u0456 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0438 \u0430\u0431\u043e \u043d\u0435\u043c\u043e\u0436\u043b\u0438\u0432\u043e \u0456\u0434\u0435\u043d\u0442\u0438\u0444\u0456\u043a\u0443\u0432\u0430\u0442\u0438')], default='other', max_length=25, verbose_name='\u0422\u0438\u043f \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='contacts',
            field=models.TextField(blank=True, max_length=512, verbose_name="\u0412\u0430\u0448\u0435 \u0456\u043c'\u044f \u0442\u0430 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0438"),
        ),
    ]
