# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_auto_20181206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person2company',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='\u0420\u043e\u0437\u043c\u0456\u0440 \u0447\u0430\u0441\u0442\u043a\u0438 (\u0432\u0456\u0434\u0441\u043e\u0442\u043a\u0438)'),
        ),
    ]
