# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 15:06
from __future__ import unicode_literals

from django.db import migrations, models

def publish_everything(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    Person = apps.get_model("core", "Person")

    Person.objects.all().update(publish=True)
    Company.objects.all().update(publish=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_auto_20190529_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0456\u043a\u0443\u0432\u0430\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='person',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0456\u043a\u0443\u0432\u0430\u0442\u0438'),
        ),

        migrations.RunPython(
            publish_everything, reverse_code=migrations.RunPython.noop),
    ]
