# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-15 22:46
from __future__ import unicode_literals

from django.db import migrations


def set_country(apps, schema_editor):
    country = apps.get_model("core", "Country")

    orders = {
        "RU": 1,
        "DE": 2,
        "AT": 3,
        "CY": 4,
        "GB": 5,
        "EE": 6,
        "LV": 7,
        "US": 8,
        "FR": 9,
        "ES": 10,
    }

    for iso2, order in orders.items():
        cnt = country.objects.get(iso2=iso2)
        cnt.order = order
        cnt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_auto_20181216_0046'),
    ]

    operations = [
        migrations.RunPython(set_country, reverse_code=migrations.RunPython.noop)
    ]
