# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


def mark_providers(apps, schema_editor):
    Company2Company = apps.get_model("core", "Company2Company")
    Company = apps.get_model("core", "Company")

    Company.objects.filter(
        pk__in=Company2Company.objects.filter(
            relationship_type__in=["Секретар", "Директор"]
        )
        .distinct("to_company")
        .values_list("to_company", flat=True)
    ).update(service_provider=True)


class Migration(migrations.Migration):

    dependencies = [("core", "0161_auto_20190801_2323")]

    operations = [
        migrations.RunPython(mark_providers, reverse_code=migrations.RunPython.noop)
    ]
