# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-01 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20190801_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subject_of_monitoring',
        ),
        migrations.RemoveField(
            model_name='company',
            name='works_for_peps',
        ),
        migrations.AlterField(
            model_name='company',
            name='affiliated_with_pep',
            field=models.BooleanField(default=False, verbose_name="\u041f\u043e\u0432'\u044f\u0437\u0430\u043d\u0430 \u0437 \u041f\u0415\u041f"),
        ),
        migrations.AlterField(
            model_name='company',
            name='political_party',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0430\u0440\u0442\u0456\u044f'),
        ),
        migrations.AlterField(
            model_name='company',
            name='public_office',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u0440\u0436.\u043e\u0440\u0433\u0430\u043d'),
        ),
        migrations.AlterField(
            model_name='company',
            name='service_provider',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430\u0434\u0430\u0432\u0430\u0447 \u043f\u043e\u0441\u043b\u0443\u0433'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_enterprise',
            field=models.BooleanField(default=False, verbose_name='\u0414\u0435\u0440\u0436. \u0432\u043b\u0430\u0441\u043d\u0456\u0441\u0442\u044c'),
        ),
    ]
