# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-10 13:56
from __future__ import unicode_literals

from django.db import migrations
from core.models import Person


def regenerate_transliterations(apps, schema_editor):
    for p in Person.objects.nocache().iterator():
        # Just need to trigger code to regenerate all the names
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20190314_1105'),
    ]

    operations = [
        migrations.RunPython(regenerate_transliterations, reverse_code=migrations.RunPython.noop)
    ]
